openapi: 3.0.3
info:
  title: Recipe Generator
  version: 2.0.0
  description: 이 API는 사용자가 현재 갖고 있는 식재료들, 현재 사용 가능한 조리기구, 그리고 식재료 추가 가능 여부를 입력받아 ChatGPT를
    이용하여 현재 만들 수 있는 레시피를 추천해줍니다.
paths:
  /accounts/join/:
    post:
      operationId: accounts_join_create
      tags:
      - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Register'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Register'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JWT'
          description: ''
  /accounts/join/resend-email/:
    post:
      operationId: accounts_join_resend_email_create
      tags:
      - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResendEmailVerification'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ResendEmailVerification'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ResendEmailVerification'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestAuthDetail'
          description: ''
  /accounts/join/verify-email/:
    post:
      operationId: accounts_join_verify_email_create
      tags:
      - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyEmail'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/VerifyEmail'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/VerifyEmail'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestAuthDetail'
          description: ''
  /accounts/login/:
    post:
      operationId: accounts_login_create
      description: |-
        Check the credentials and return the REST Token
        if the credentials are valid and authenticated.
        Calls Django Auth login method to register User ID
        in Django session framework

        Accept the following POST parameters: username, password
        Return the REST Framework Token Object's key.
      tags:
      - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Login'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Login'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JWT'
          description: ''
  /accounts/logout/:
    post:
      operationId: accounts_logout_create
      description: |-
        Calls Django logout method and delete the Token object
        assigned to the current User object.

        Accepts/Returns nothing.
      tags:
      - accounts
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestAuthDetail'
          description: ''
  /accounts/password/change/:
    post:
      operationId: accounts_password_change_create
      description: |-
        Calls Django Auth SetPasswordForm save method.

        Accepts the following POST parameters: new_password1, new_password2
        Returns the success/fail message.
      tags:
      - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordChange'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PasswordChange'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PasswordChange'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestAuthDetail'
          description: ''
  /accounts/password/reset/:
    post:
      operationId: accounts_password_reset_create
      description: |-
        Calls Django Auth PasswordResetForm save method.

        Accepts the following POST parameters: email
        Returns the success/fail message.
      tags:
      - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordReset'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PasswordReset'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PasswordReset'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestAuthDetail'
          description: ''
  /accounts/password/reset/confirm/:
    post:
      operationId: accounts_password_reset_confirm_create
      description: |-
        Password reset e-mail link is confirmed, therefore
        this resets the user's password.

        Accepts the following POST parameters: token, uid,
            new_password1, new_password2
        Returns the success/fail message.
      tags:
      - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordResetConfirm'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PasswordResetConfirm'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PasswordResetConfirm'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestAuthDetail'
          description: ''
  /accounts/token/refresh/:
    post:
      operationId: accounts_token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /accounts/token/verify/:
    post:
      operationId: accounts_token_verify_create
      description: |-
        Takes a token and indicates if it is valid.  This view provides no
        information about a token's fitness for a particular use.
      tags:
      - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenVerify'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenVerify'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenVerify'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenVerify'
          description: ''
  /accounts/user/:
    get:
      operationId: accounts_user_retrieve
      description: |-
        Reads and updates UserModel fields
        Accepts GET, PUT, PATCH methods.

        Default accepted fields: username, first_name, last_name
        Default display fields: pk, username, email, first_name, last_name
        Read-only fields: pk, email

        Returns UserModel fields.
      tags:
      - accounts
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetails'
          description: ''
    put:
      operationId: accounts_user_update
      description: |-
        Reads and updates UserModel fields
        Accepts GET, PUT, PATCH methods.

        Default accepted fields: username, first_name, last_name
        Default display fields: pk, username, email, first_name, last_name
        Read-only fields: pk, email

        Returns UserModel fields.
      tags:
      - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDetails'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserDetails'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserDetails'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetails'
          description: ''
    patch:
      operationId: accounts_user_partial_update
      description: |-
        Reads and updates UserModel fields
        Accepts GET, PUT, PATCH methods.

        Default accepted fields: username, first_name, last_name
        Default display fields: pk, username, email, first_name, last_name
        Read-only fields: pk, email

        Returns UserModel fields.
      tags:
      - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedUserDetails'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedUserDetails'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedUserDetails'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetails'
          description: ''
  /api/schema/:
    get:
      operationId: api_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - api
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /recipe/:
    get:
      operationId: recipe_list
      description: 요청을 보낸 유저가 생성한 레시피들을 전부 가져옵니다. 페이지네이션을 이용하여 한 페이지에 최대 10개씩 보여줍니다.
        로그인을 한 유저만 이용 가능합니다.
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      tags:
      - recipe
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedRecipeList'
              examples:
                레시피목록조회:
                  value:
                    count: 123
                    next: http://api.example.org/accounts/?page=4
                    previous: http://api.example.org/accounts/?page=2
                    results:
                    - id: 1
                      input_ingredient: 밀가루, 감자, 버섯
                      oven: false
                      air_fryer: false
                      gas_stove: true
                      microwave: false
                      additional: true
                      content: '밀가루, 감자, 버섯을/를 이용한 요리의 레시피를 한 가지 알려줘. 가열할 수 있는 기구는
                        가스레인지만 있어. 레피시명:, 재료:, 요리방법: 순서로 알려주고 다른 말은 하지 말아줘.'
                      answer: |-
                        레시피명: 감자 버섯 전

                        재료:
                        - 밀가루 1컵
                        - 감자 2개 (중간 크기)
                        - 버섯 100g
                        - 식용유
                        - 소금
                        - 후추

                        요리방법:
                        1. 감자를 깨끗이 씻어 껍질을 벗긴 후, 가늘게 채 썰어주세요.
                        2. 버섯은 깨끗이 닦아서 얇게 슬라이스 해주세요.
                        3. 밀가루를 그릇에 넣고, 소금과 후추를 넣어 가루에 골고루 섞어주세요.
                        4. 감자와 버섯을 가루에 넣고, 가루에 잘 묻히도록 버무려주세요.
                        5. 가스레인지에 팬을 달고, 중간 불로 예열해주세요.
                        6. 예열이 끝나면 팬에 식용유를 넉넉히 두르고, 가루에 버무려진 감자와 버섯을 올려주세요.
                        7. 한쪽 면이 바삭하게 익을 때까지 약 3분 정도 구워주세요.
                        8. 접시에 옮겨서 소금과 후추로 간을 해주세요.
                        9. 남은 감자와 버섯도 같은 방법으로 전을 만들어주세요.
                        10. 완성된 감자 버섯 전을 맛있게 즐겨주세요.
                      title: 감자 버섯 전
                      ingredient: 밀가루 1컵, 감자 2개 (중간 크기), 버섯 100g, 식용유, 소금, 후추
                      recipe: <li>감자를 깨끗이 씻어 껍질을 벗긴 후, 가늘게 채 썰어주세요.</li><li>버섯은 깨끗이
                        닦아서 얇게 슬라이스 해주세요.</li><li>밀가루를 그릇에 넣고, 소금과 후추를 넣어 가루에 골고루
                        섞어주세요.</li><li>감자와 버섯을 가루에 넣고, 가루에 잘 묻히도록 버무려주세요.</li><li>가스레인지에
                        팬을 달고, 중간 불로 예열해주세요.</li><li>예열이 끝나면 팬에 식용유를 넉넉히 두르고, 가루에
                        버무려진 감자와 버섯을 올려주세요.</li><li>한쪽 면이 바삭하게 익을 때까지 약 </li><li>정도
                        구워주세요.</li><li>접시에 옮겨서 소금과 후추로 간을 해주세요.</li><li>남은 감자와 버섯도
                        같은 방법으로 전을 만들어주세요.</li><li>완성된 감자 버섯 전을 맛있게 즐겨주세요.</li>
                      img_url: https://images.unsplash.com/photo-1597585588073-091447702d37?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1MzIzMjZ8MHwxfHNlYXJjaHwxfHwlRUElQjAlOTAlRUMlOUUlOTAlMjAlRUIlQjIlODQlRUMlODQlQUYlMjAlRUMlQTAlODR8a298MHx8fHwxNzAxMjMyNDUxfDA&ixlib=rb-4.0.3&q=80&w=1080
                      created_at: '2023-11-28T18:22:45.393447+09:00'
                      updated_at: '2023-11-29'
                      user: 2
                  summary: 레시피 목록 조회
          description: ''
    post:
      operationId: recipe_create
      description: 현재 가지고 있는 **식재료**, 사용 가능한 **조리기구**, 재료 **추가여부**를 입력 받아 추천 레시피를
        생성해줍니다.  저장하기 전에, 입력값들로 1. `chatGPT`에게 물어볼 말을 만들고, 2. `chatGPT`에게 물어본 후, 3.
        추천 받은 레시피를 **요리 제목**, **필요한 재료**, **만드는 방법**으로 나누고, 4. 요리와 연관된 **사진**도 `Unsplash
        API`를 이용하여 검색해서 링크를 같이 저장합니다.  `check_usage` 데코레이터를 이용하여 유저 당 하루 5회로 **사용횟수를
        제한**합니다. 로그인을 한 유저만 이용 가능합니다.
      tags:
      - recipe
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Recipe'
            examples:
              레시피추천받기:
                value:
                  input_ingredient: 밀가루, 감자, 버섯
                  oven: false
                  air_fryer: false
                  gas_stove: true
                  microwave: false
                  additional: true
                summary: 레시피 추천 받기
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Recipe'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Recipe'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
              examples:
                추천된레시피:
                  value:
                    id: 1
                    input_ingredient: 밀가루, 감자, 버섯
                    oven: false
                    air_fryer: false
                    gas_stove: true
                    microwave: false
                    additional: true
                    content: '밀가루, 감자, 버섯을/를 이용한 요리의 레시피를 한 가지 알려줘. 가열할 수 있는 기구는 가스레인지만
                      있어. 레피시명:, 재료:, 요리방법: 순서로 알려주고 다른 말은 하지 말아줘.'
                    answer: |-
                      레시피명: 감자 버섯 전

                      재료:
                      - 밀가루 1컵
                      - 감자 2개 (중간 크기)
                      - 버섯 100g
                      - 식용유
                      - 소금
                      - 후추

                      요리방법:
                      1. 감자를 깨끗이 씻어 껍질을 벗긴 후, 가늘게 채 썰어주세요.
                      2. 버섯은 깨끗이 닦아서 얇게 슬라이스 해주세요.
                      3. 밀가루를 그릇에 넣고, 소금과 후추를 넣어 가루에 골고루 섞어주세요.
                      4. 감자와 버섯을 가루에 넣고, 가루에 잘 묻히도록 버무려주세요.
                      5. 가스레인지에 팬을 달고, 중간 불로 예열해주세요.
                      6. 예열이 끝나면 팬에 식용유를 넉넉히 두르고, 가루에 버무려진 감자와 버섯을 올려주세요.
                      7. 한쪽 면이 바삭하게 익을 때까지 약 3분 정도 구워주세요.
                      8. 접시에 옮겨서 소금과 후추로 간을 해주세요.
                      9. 남은 감자와 버섯도 같은 방법으로 전을 만들어주세요.
                      10. 완성된 감자 버섯 전을 맛있게 즐겨주세요.
                    title: 감자 버섯 전
                    ingredient: 밀가루 1컵, 감자 2개 (중간 크기), 버섯 100g, 식용유, 소금, 후추
                    recipe: <li>감자를 깨끗이 씻어 껍질을 벗긴 후, 가늘게 채 썰어주세요.</li><li>버섯은 깨끗이
                      닦아서 얇게 슬라이스 해주세요.</li><li>밀가루를 그릇에 넣고, 소금과 후추를 넣어 가루에 골고루 섞어주세요.</li><li>감자와
                      버섯을 가루에 넣고, 가루에 잘 묻히도록 버무려주세요.</li><li>가스레인지에 팬을 달고, 중간 불로 예열해주세요.</li><li>예열이
                      끝나면 팬에 식용유를 넉넉히 두르고, 가루에 버무려진 감자와 버섯을 올려주세요.</li><li>한쪽 면이 바삭하게
                      익을 때까지 약 </li><li>정도 구워주세요.</li><li>접시에 옮겨서 소금과 후추로 간을 해주세요.</li><li>남은
                      감자와 버섯도 같은 방법으로 전을 만들어주세요.</li><li>완성된 감자 버섯 전을 맛있게 즐겨주세요.</li>
                    img_url: https://images.unsplash.com/photo-1597585588073-091447702d37?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1MzIzMjZ8MHwxfHNlYXJjaHwxfHwlRUElQjAlOTAlRUMlOUUlOTAlMjAlRUIlQjIlODQlRUMlODQlQUYlMjAlRUMlQTAlODR8a298MHx8fHwxNzAxMjMyNDUxfDA&ixlib=rb-4.0.3&q=80&w=1080
                    created_at: '2023-11-28T18:22:45.393447+09:00'
                    updated_at: '2023-11-29'
                    user: 2
                  summary: 추천된 레시피
          description: ''
  /recipe/{id}/:
    get:
      operationId: recipe_retrieve
      description: '`id`를 이용해서 해당 레시피 정보를 가져옵니다. 로그인을 한 유저가 본인의 레시피만 가져올 수 있습니다.'
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this recipe.
        required: true
      tags:
      - recipe
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
              examples:
                추천된레시피:
                  value:
                    id: 1
                    input_ingredient: 밀가루, 감자, 버섯
                    oven: false
                    air_fryer: false
                    gas_stove: true
                    microwave: false
                    additional: true
                    content: '밀가루, 감자, 버섯을/를 이용한 요리의 레시피를 한 가지 알려줘. 가열할 수 있는 기구는 가스레인지만
                      있어. 레피시명:, 재료:, 요리방법: 순서로 알려주고 다른 말은 하지 말아줘.'
                    answer: |-
                      레시피명: 감자 버섯 전

                      재료:
                      - 밀가루 1컵
                      - 감자 2개 (중간 크기)
                      - 버섯 100g
                      - 식용유
                      - 소금
                      - 후추

                      요리방법:
                      1. 감자를 깨끗이 씻어 껍질을 벗긴 후, 가늘게 채 썰어주세요.
                      2. 버섯은 깨끗이 닦아서 얇게 슬라이스 해주세요.
                      3. 밀가루를 그릇에 넣고, 소금과 후추를 넣어 가루에 골고루 섞어주세요.
                      4. 감자와 버섯을 가루에 넣고, 가루에 잘 묻히도록 버무려주세요.
                      5. 가스레인지에 팬을 달고, 중간 불로 예열해주세요.
                      6. 예열이 끝나면 팬에 식용유를 넉넉히 두르고, 가루에 버무려진 감자와 버섯을 올려주세요.
                      7. 한쪽 면이 바삭하게 익을 때까지 약 3분 정도 구워주세요.
                      8. 접시에 옮겨서 소금과 후추로 간을 해주세요.
                      9. 남은 감자와 버섯도 같은 방법으로 전을 만들어주세요.
                      10. 완성된 감자 버섯 전을 맛있게 즐겨주세요.
                    title: 감자 버섯 전
                    ingredient: 밀가루 1컵, 감자 2개 (중간 크기), 버섯 100g, 식용유, 소금, 후추
                    recipe: <li>감자를 깨끗이 씻어 껍질을 벗긴 후, 가늘게 채 썰어주세요.</li><li>버섯은 깨끗이
                      닦아서 얇게 슬라이스 해주세요.</li><li>밀가루를 그릇에 넣고, 소금과 후추를 넣어 가루에 골고루 섞어주세요.</li><li>감자와
                      버섯을 가루에 넣고, 가루에 잘 묻히도록 버무려주세요.</li><li>가스레인지에 팬을 달고, 중간 불로 예열해주세요.</li><li>예열이
                      끝나면 팬에 식용유를 넉넉히 두르고, 가루에 버무려진 감자와 버섯을 올려주세요.</li><li>한쪽 면이 바삭하게
                      익을 때까지 약 </li><li>정도 구워주세요.</li><li>접시에 옮겨서 소금과 후추로 간을 해주세요.</li><li>남은
                      감자와 버섯도 같은 방법으로 전을 만들어주세요.</li><li>완성된 감자 버섯 전을 맛있게 즐겨주세요.</li>
                    img_url: https://images.unsplash.com/photo-1597585588073-091447702d37?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1MzIzMjZ8MHwxfHNlYXJjaHwxfHwlRUElQjAlOTAlRUMlOUUlOTAlMjAlRUIlQjIlODQlRUMlODQlQUYlMjAlRUMlQTAlODR8a298MHx8fHwxNzAxMjMyNDUxfDA&ixlib=rb-4.0.3&q=80&w=1080
                    created_at: '2023-11-28T18:22:45.393447+09:00'
                    updated_at: '2023-11-29'
                    user: 2
                  summary: 추천된 레시피
          description: ''
    patch:
      operationId: recipe_partial_update
      description: '`id`를 이용해서 해당 레시피 객체에 새로운 입력값으로 새로운 레시피를 추천받아 정보를 업데이트합니다. 전체
        수정이 아닌 부분만 수정이 될 수도 있으므로 `PUT`대신 `PATCH`를 이용합니다. 로그인을 한 유저가 본인의 레시피만 수정할 수
        있습니다.'
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this recipe.
        required: true
      tags:
      - recipe
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedRecipe'
            examples:
              레시피추천받기:
                value:
                  input_ingredient: 밀가루, 감자, 버섯
                  oven: false
                  air_fryer: false
                  gas_stove: true
                  microwave: false
                  additional: true
                summary: 레시피 추천 받기
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedRecipe'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedRecipe'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
              examples:
                추천된레시피:
                  value:
                    id: 1
                    input_ingredient: 밀가루, 감자, 버섯
                    oven: false
                    air_fryer: false
                    gas_stove: true
                    microwave: false
                    additional: true
                    content: '밀가루, 감자, 버섯을/를 이용한 요리의 레시피를 한 가지 알려줘. 가열할 수 있는 기구는 가스레인지만
                      있어. 레피시명:, 재료:, 요리방법: 순서로 알려주고 다른 말은 하지 말아줘.'
                    answer: |-
                      레시피명: 감자 버섯 전

                      재료:
                      - 밀가루 1컵
                      - 감자 2개 (중간 크기)
                      - 버섯 100g
                      - 식용유
                      - 소금
                      - 후추

                      요리방법:
                      1. 감자를 깨끗이 씻어 껍질을 벗긴 후, 가늘게 채 썰어주세요.
                      2. 버섯은 깨끗이 닦아서 얇게 슬라이스 해주세요.
                      3. 밀가루를 그릇에 넣고, 소금과 후추를 넣어 가루에 골고루 섞어주세요.
                      4. 감자와 버섯을 가루에 넣고, 가루에 잘 묻히도록 버무려주세요.
                      5. 가스레인지에 팬을 달고, 중간 불로 예열해주세요.
                      6. 예열이 끝나면 팬에 식용유를 넉넉히 두르고, 가루에 버무려진 감자와 버섯을 올려주세요.
                      7. 한쪽 면이 바삭하게 익을 때까지 약 3분 정도 구워주세요.
                      8. 접시에 옮겨서 소금과 후추로 간을 해주세요.
                      9. 남은 감자와 버섯도 같은 방법으로 전을 만들어주세요.
                      10. 완성된 감자 버섯 전을 맛있게 즐겨주세요.
                    title: 감자 버섯 전
                    ingredient: 밀가루 1컵, 감자 2개 (중간 크기), 버섯 100g, 식용유, 소금, 후추
                    recipe: <li>감자를 깨끗이 씻어 껍질을 벗긴 후, 가늘게 채 썰어주세요.</li><li>버섯은 깨끗이
                      닦아서 얇게 슬라이스 해주세요.</li><li>밀가루를 그릇에 넣고, 소금과 후추를 넣어 가루에 골고루 섞어주세요.</li><li>감자와
                      버섯을 가루에 넣고, 가루에 잘 묻히도록 버무려주세요.</li><li>가스레인지에 팬을 달고, 중간 불로 예열해주세요.</li><li>예열이
                      끝나면 팬에 식용유를 넉넉히 두르고, 가루에 버무려진 감자와 버섯을 올려주세요.</li><li>한쪽 면이 바삭하게
                      익을 때까지 약 </li><li>정도 구워주세요.</li><li>접시에 옮겨서 소금과 후추로 간을 해주세요.</li><li>남은
                      감자와 버섯도 같은 방법으로 전을 만들어주세요.</li><li>완성된 감자 버섯 전을 맛있게 즐겨주세요.</li>
                    img_url: https://images.unsplash.com/photo-1597585588073-091447702d37?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1MzIzMjZ8MHwxfHNlYXJjaHwxfHwlRUElQjAlOTAlRUMlOUUlOTAlMjAlRUIlQjIlODQlRUMlODQlQUYlMjAlRUMlQTAlODR8a298MHx8fHwxNzAxMjMyNDUxfDA&ixlib=rb-4.0.3&q=80&w=1080
                    created_at: '2023-11-28T18:22:45.393447+09:00'
                    updated_at: '2023-11-29'
                    user: 2
                  summary: 추천된 레시피
          description: ''
    delete:
      operationId: recipe_destroy
      description: '`id`를 이용해서 해당 레시피 정보를 삭제합니다. 로그인을 한 유저가 본인의 레시피만 삭제할 수 있습니다.'
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this recipe.
        required: true
      tags:
      - recipe
      security:
      - jwtAuth: []
      responses:
        '204':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
          description: ''
  /recipe/all/:
    delete:
      operationId: recipe_all_destroy
      description: 요청을 보낸 유저가 생성했던 레시피를 전체 삭제합니다. 로그인을 한 유저가 본인의 레시피들만 전체 삭제할 수 있습니다.
      tags:
      - recipe
      security:
      - jwtAuth: []
      responses:
        '204':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
          description: ''
components:
  schemas:
    JWT:
      type: object
      description: Serializer for JWT authentication.
      properties:
        access_token:
          type: string
        refresh_token:
          type: string
        user:
          $ref: '#/components/schemas/UserDetails'
      required:
      - access_token
      - refresh_token
      - user
    Login:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
      required:
      - password
    PaginatedRecipeList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Recipe'
    PasswordChange:
      type: object
      properties:
        new_password1:
          type: string
          maxLength: 128
        new_password2:
          type: string
          maxLength: 128
      required:
      - new_password1
      - new_password2
    PasswordReset:
      type: object
      description: Serializer for requesting a password reset e-mail.
      properties:
        email:
          type: string
          format: email
      required:
      - email
    PasswordResetConfirm:
      type: object
      description: Serializer for confirming a password reset attempt.
      properties:
        new_password1:
          type: string
          maxLength: 128
        new_password2:
          type: string
          maxLength: 128
        uid:
          type: string
        token:
          type: string
      required:
      - new_password1
      - new_password2
      - token
      - uid
    PatchedRecipe:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        input_ingredient:
          type: string
        oven:
          type: boolean
        air_fryer:
          type: boolean
        gas_stove:
          type: boolean
        microwave:
          type: boolean
        additional:
          type: boolean
        content:
          type: string
        answer:
          type: string
        title:
          type: string
          maxLength: 50
        ingredient:
          type: string
        recipe:
          type: string
        img_url:
          type: string
          format: uri
          maxLength: 400
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date
          readOnly: true
        user:
          type: integer
          readOnly: true
    PatchedUserDetails:
      type: object
      description: User model w/o password
      properties:
        pk:
          type: integer
          readOnly: true
          title: ID
        email:
          type: string
          format: email
          readOnly: true
          title: 이메일 주소
        first_name:
          type: string
          title: 이름
          maxLength: 150
        last_name:
          type: string
          title: 성
          maxLength: 150
    Recipe:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        input_ingredient:
          type: string
        oven:
          type: boolean
        air_fryer:
          type: boolean
        gas_stove:
          type: boolean
        microwave:
          type: boolean
        additional:
          type: boolean
        content:
          type: string
        answer:
          type: string
        title:
          type: string
          maxLength: 50
        ingredient:
          type: string
        recipe:
          type: string
        img_url:
          type: string
          format: uri
          maxLength: 400
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date
          readOnly: true
        user:
          type: integer
          readOnly: true
      required:
      - created_at
      - id
      - input_ingredient
      - updated_at
      - user
    Register:
      type: object
      properties:
        username:
          type: string
          maxLength: 0
          minLength: 1
        email:
          type: string
          format: email
        password1:
          type: string
          writeOnly: true
        password2:
          type: string
          writeOnly: true
      required:
      - email
      - password1
      - password2
    ResendEmailVerification:
      type: object
      properties:
        email:
          type: string
          format: email
      required:
      - email
    RestAuthDetail:
      type: object
      properties:
        detail:
          type: string
          readOnly: true
      required:
      - detail
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          writeOnly: true
      required:
      - access
      - refresh
    TokenVerify:
      type: object
      properties:
        token:
          type: string
          writeOnly: true
      required:
      - token
    UserDetails:
      type: object
      description: User model w/o password
      properties:
        pk:
          type: integer
          readOnly: true
          title: ID
        email:
          type: string
          format: email
          readOnly: true
          title: 이메일 주소
        first_name:
          type: string
          title: 이름
          maxLength: 150
        last_name:
          type: string
          title: 성
          maxLength: 150
      required:
      - email
      - pk
    VerifyEmail:
      type: object
      properties:
        key:
          type: string
      required:
      - key
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
